"""Re-export public tool callables for server/test compatibility."""
from __future__ import annotations

from src.mcp.tools.administration import (
    create,
    delete,
    get_operation_log,
    list_recent_operations,
    preview_operation,
    query_operation_logs,
    restore_knowledge,
    undo_operation,
    update,
)
from src.mcp.tools.graph import get_source_graph, graph_traverse
from src.mcp.tools.ingest import (
    cancel_job,
    create_ingest_job,
    get_job,
    index_path,
    ingest_file,
    ingest_url,
    list_jobs,
    list_knowledge,
    reindex_all,
    tags,
)
from src.mcp.tools.memory import (
    delete_memory,
    extract_tasks_from_doc,
    recall_facts,
    remember_fact,
    search_decisions,
    summarize_recent_changes,
    update_project_context,
)
from src.mcp.tools.operations import (
    cancel_async_job,
    create_async_job,
    get_async_job,
    list_async_jobs,
)
from src.mcp.tools.retrieval import (
    _do_ask,
    ask,
    ask_with_query,
    auto_tag,
    execute_query,
    explain_query,
    get_trace,
    kb_capabilities,
    kb_health_check,
    ping,
    read,
    route_query,
    search,
    search_fulltext,
    structured_query,
)
from src.mcp.tools.wiki import (
    delete_wiki_page,
    fix_dead_references,
    save_to_wiki,
    wiki_approve,
    wiki_deprecate,
    wiki_lint,
    wiki_list_versions,
    wiki_reject,
    wiki_restore_version,
    wiki_submit_review,
    wiki_workflow_history,
)

# Side-effect: load domain modules so tool_definition registry is populated
from src.mcp.tools import (  # noqa: F401
    administration,
    graph,
    ingest,
    memory,
    operations,
    retrieval,
    wiki,
)

__all__ = [
    "_do_ask",
    "ask",
    "ask_with_query",
    "auto_tag",
    "cancel_async_job",
    "cancel_job",
    "create",
    "create_async_job",
    "create_ingest_job",
    "delete",
    "delete_memory",
    "delete_wiki_page",
    "execute_query",
    "explain_query",
    "extract_tasks_from_doc",
    "fix_dead_references",
    "get_async_job",
    "get_job",
    "get_operation_log",
    "get_source_graph",
    "get_trace",
    "graph_traverse",
    "index_path",
    "ingest_file",
    "ingest_url",
    "kb_capabilities",
    "kb_health_check",
    "list_async_jobs",
    "list_jobs",
    "list_knowledge",
    "list_recent_operations",
    "ping",
    "preview_operation",
    "query_operation_logs",
    "read",
    "recall_facts",
    "reindex_all",
    "remember_fact",
    "restore_knowledge",
    "route_query",
    "save_to_wiki",
    "search",
    "search_decisions",
    "search_fulltext",
    "structured_query",
    "summarize_recent_changes",
    "tags",
    "undo_operation",
    "update",
    "update_project_context",
    "wiki_approve",
    "wiki_deprecate",
    "wiki_lint",
    "wiki_list_versions",
    "wiki_reject",
    "wiki_restore_version",
    "wiki_submit_review",
    "wiki_workflow_history",
]
